version: "3.9"

services:
  plandex_common:
    container_name: plandex_common
    build:
      context: .
      dockerfile: Dockerfile.common
      args:
        USER: ${USER}
        USER_ID: 1010
        GROUP_ID: 1010
    image: plandex_common
    ports:
      - 5900:5900
      - 5901:5901
      - 6079:6079
      - 6080:6080
      - 8000:8000
    environment:
      - VNC_PASSWORD=your_password
    command: ["true"] # should not up service

  plandex-backend:
    container_name: plandex-backend
    image: plandex_common:latest
    depends_on:
      - plandex_common
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LM_MODEL="claude-3-haiku-20240307"
    networks:
      - plandex-subnetwork
    entrypoint: ["bash", "-c", "/app/scripts/plandex/setup_plandex.sh"]
    volumes:
      - ./scripts:/app/scripts
    tty: true

  plandex-frontend:
    container_name: plandex-frontend
    image: plandex_common:latest
    depends_on:
      - plandex_common
    expose:
      - 11434
    ports:
      - 11434:11434
    networks:
      - plandex-subnetwork
    entrypoint: ["make", "run"]
    tty: true

  plandex-test:
    container_name: plandex-test
    image: plandex_common:latest
    depends_on:
      - plandex_common
    networks:
      - plandex-subnetwork
    entrypoint: ["bash", "-i"]
    tty: true

networks:
  plandex-subnetwork:

volumes:
  plandex-backend-dbstore:
