version: "3.9"

services:
  opendevin-backend-engine:
    image: ghcr.io/opendevin/sandbox:latest
    expose:
      - 1337
    ports:
      - 1337:1337
    environment:
      - LLM_API_KEY=""
      - LM_MODEL="claude-3-haiku-20240307"
    networks:
      - opendevin-subnetwork
    entrypoint: ["true"] # should not up service
    volumes:
      - ./scripts:/app/scripts
    tty: true

  opendevin-frontend-app:
    image: ghcr.io/opendevin/sandbox:latest
    expose:
      - 11434
    ports:
      - 11434:11434
    networks:
      - opendevin-subnetwork
    entrypoint: ["make", "run"]
    tty: true

  opendevin-test:
    image: ghcr.io/opendevin/sandbox:latest
    networks:
      - opendevin-subnetwork
    entrypoint: ["bash", "-i"]
    tty: true

networks:
  opendevin-subnetwork:

volumes:
  opendevin-backend-dbstore:
